# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5359da0305979d7cc870bd19810ee95b3d62d5ed155c8d307236845c8279a3914ebf48b862a9f22f0805aa79f21bee5dd2ca80eb41fc43ddbe99155955594e10

test:
  secret_key_base: 883b1c94ad6ec8b7df5e56d72ce19b12bf8699bd7b5cf312c9dca6db8f0d6ccf1234d0c0e1dce64410ca211206dc9cb9e06b59e2fcf73b315deadcf8df7c6bf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
